#pragma once

#include <iostream>
#include <sstream>
#include <unordered_map>
#include <unordered_set>

#include "arch.hpp"
#include "protogen.hpp"

namespace pj {

class SourceGenerator {
 public:
  SourceGenerator(const SourceId& outer_namespace)
      : outer_namespace_(outer_namespace), counter_(0) {}

  void addTypedef(const SourceId& name, types::ValueType type);

  // Recursively add subtypes if not added for wire types.
  void addProtocol(const SourceId& name, types::ProtocolType proto);
  void addComposite(types::ValueType type, bool is_external = false);

  void addPortal(const SourceId& ns, const ParsedProtoFile::Portal& portal);

  void generate(const std::filesystem::path& header_path, std::ostream& output,
                std::ostream* cpp,
                const std::vector<std::filesystem::path>& imports);

 private:
  enum class Region { kDefs, kBuilders, kCpp };

  // The type domain of the composite type that is currently being generated.
  // Host types have struct and enum definitions generated, and their build
  // methods are based on the host compiler's layout decisions. Wire types only
  // have build methods generated describing the exact layout of the MLIR types
  // as provided.
  enum class Domain { kUnset, kHost, kWire };

  void pushDomain(Domain domain) {
    assert(domain != Domain::kUnset);
    assert((depth_ == 0 && domain_ == Domain::kUnset) || domain_ == domain);
    domain_ = domain;
    depth_++;
  }

  void pushDomain(types::DomainAttr domain) {
    auto new_domain = Domain::kUnset;
    // .pj files are parsed into the InternalDomain, because the types do not
    // actually correspond to an actual in-memory type. However, since the
    // generated C++ code does describe an in-memory type, it should be
    // generated in HostDomain.
    if (domain.isa<types::InternalDomainAttr>()) {
      new_domain = Domain::kHost;
    } else if (domain.isa<types::WireDomainAttr>()) {
      new_domain = Domain::kWire;
    }
    pushDomain(new_domain);
  }

  void popDomain() {
    if (--depth_ == 0) {
      domain_ = Domain::kUnset;
    }
  }

  // Adds the type as well as all of its subtypes.
  void addType(types::ValueType type);

  std::stringstream& stream() {
    if (region_ == Region::kDefs) return defs_;
    if (region_ == Region::kBuilders) return builders_;
    if (region_ == Region::kCpp) return cpp_;
    UNREACHABLE();
  }

  std::string getUniqueName() { return "_" + std::to_string(counter_++); }

  template <typename Name>
  void beginNamespaceOf(const Name& name, bool is_namespace_name = false) {
    for (std::string_view space : outer_namespace_) {
      stream() << "namespace " << space << "{\n";
    }
    for (size_t i = 0; i < name.size() - !is_namespace_name; ++i) {
      stream() << "namespace " << std::string_view(name[i]) << "{\n";
    }
  }

  template <typename Name>
  void endNamespaceOf(const Name& name, bool is_namespace_name = false) {
    for (size_t i = 0;
         i < outer_namespace_.size() + name.size() - !is_namespace_name; ++i) {
      stream() << "}\n";
    }
    stream() << "\n";
  }

  template <typename Name>
  std::string getNameAsString(const Name& name, const char* delim = "::") {
    std::stringstream str;
    for (auto& p : outer_namespace_) str << delim << p;
    for (auto& p : name) str << delim << std::string_view(p);
    return str.str();
  }

  template <typename Name>
  void printName(const Name& name) {
    stream() << getNameAsString(name);
  }

  void printIntTypeRef(Width width, Sign sign);
  void printTypeRef(types::ValueType type);
  void printPlanName(std::ostream& os, const SourceId& plan);

  std::ostream& printDecoderSig(std::ostream& os, const std::string& name,
                                const ParsedProtoFile::Portal::Decoder& decoder,
                                bool state_template, bool is_declaration);

  // Generates a variable containing a handle to a runtime type generated using
  // the type of the in-memory type, obtained using decltype. Expects a
  // PJContext* in scope with name ctx.
  std::string createTypeHandleFromDecl(std::string decl);

  // Generates a variable containing a handle to a runtime type generated by
  // explicitly calling the PJ API functions with the provided type information.
  // Assumes that the BuildPJType specializations available for nominal types
  // corresponds correctly to the provided type information. Expects a
  // PJContext* in scope with name ctx.
  std::string createTypeHandleFromType(types::ValueType type);

  // Generates code which returns a pj::runtime::Protocol object for the
  // provided head and tag path. If create_handle is provided, stores the result
  // in a variable and returns the name of the variable. Expects a
  // pj::runtime::Context in scope with name ctx.
  std::string createProtocol(ParsedProtoFile::Portal::Protocol proto,
                             bool create_handle);

  std::string buildStringArray(Span<llvm::StringRef> arr);

  void addStructDef(types::StructType type, bool decl_only);
  void addStructBuilder(types::StructType type, bool is_external);
  void addStruct(types::StructType type, bool is_external);

  void addVariantDef(types::VariantType type, bool has_value, Width tag_width,
                     bool decl_only);
  void addVariantBuilder(types::VariantType type, bool has_value,
                         Width tag_width, bool is_external);
  void addVariant(types::VariantType type, bool is_external);
  void addJitClass(const SourceId& ns, const ParsedProtoFile::Portal& iface,
                   const std::string& name,
                   std::optional<ParsedProtoFile::Portal::Protocol> proto);
  void addPrecompClass(const SourceId& ns, const ParsedProtoFile::Portal& iface,
                       const std::string& name,
                       ParsedProtoFile::Portal::Protocol proto);

  Region region_;
  Domain domain_ = Domain::kUnset;
  size_t depth_ = 0;
  std::stringstream defs_;
  std::stringstream builders_;
  std::stringstream cpp_;
  std::unordered_set<const void*> generated_;
  std::vector<std::string> entrypoints_;

  SourceId outer_namespace_;
  size_t counter_;
};

}  // namespace pj
